use uuid as savepoint name
vlcn-io/js pull request #32
Opened 2023-10-12 21:58 UTC by AlexErrant

The primary cause of this PR is this line from [the docs](https://www.sqlite.org/lang_savepoint.html):

> The ROLLBACK command without a TO clause rolls backs all transactions

I think the current behavior of busting out of all transactions seems too much. Note that even though the rollback causes _"The SAVEPOINT with the matching name [to] remains on the transaction stack"_, the subsequent RELEASE on L109 will (more or less) close out the transaction and commit nothing. _I think._ I've tested nothing 😅

I also made the names UUIDs because even though _"The transaction names need not be unique"_, it just _feels_ safer. Feel free to assuage me of my paranoia.

2023-10-13 15:34 UTC, tantaman commented on packages/crsqlite-wasm/src/TX.ts
> +        } finally {
oops. Good catch, finally is definitely wrong here.

2023-10-13 15:36 UTC, tantaman requested changes

2023-10-13 15:36 UTC, tantaman commented on packages/crsqlite-wasm/src/TX.ts
> +        } finally {
I don't think we want finally here.

finally will run even after `catch` which means that we'll `rollback` (if there was an exception) and then `release`. We just want to do one or the other.

What problems were you experiencing?

2023-10-13 17:08 UTC, AlexErrant commented on packages/crsqlite-wasm/src/TX.ts
> +        } finally {
Hm, let me elaborate on the OP. From the docs:

> The ROLLBACK command with a TO clause rolls back transactions going backwards in time back to the most recent SAVEPOINT with a matching name. _The SAVEPOINT with the matching name remains on the transaction stack._

Emphasis mine. Since that SAVEPOINT remains on the stack, we _must_ RELEASE to close out that savepoint.

> The RELEASE command starts with the most recent addition to the transaction stack and releases savepoints backwards in time until it releases a savepoint with a matching savepoint-name.

---

However, I'm now thinking about what happens if the ROLLBACK fails - with `finally` we RELEASE _without_ a ROLLBACK. That's undesirable. If the ROLLBACK fails, we should just throw. The new commit reflects this realization.

> What problems were you experiencing?

No problems on the application side - I started to investigate nested transactions, so just read the docs and other people's code (including this).

2023-10-16 16:27 UTC, tantaman commented on packages/crsqlite-wasm/src/TX.ts
> +          await tx.exec("RELEASE " + id);
oh interesting.. I had the completely wrong mental model of `savepoints` and didn't realize a `rollback` needs to be followed by a `release` to actually pop it off the stack o_O

Thanks for catching this.

```
sqlite> savepoint b;
sqlite> create table boo (a);
sqlite> rollback to b;
sqlite> create table bar (a);
sqlite> release b;
sqlite> .tables
bar  foo
```

2023-10-16 16:27 UTC, tantaman commented on packages/crsqlite-wasm/src/TX.ts
> +          await tx.exec("RELEASE " + id);
better illustration:

```sql
sqlite> savepoint b;
sqlite> savepoint b;
sqlite> rollback to b;
sqlite> release b;
sqlite> release b;
sqlite> release b;
Runtime error: no such savepoint: b
```

Even with `rollback` we must `release`

2023-10-16 16:27 UTC, tantaman commented on packages/crsqlite-wasm/src/TX.ts
> +    const id = crypto.randomUUID().replaceAll("-", "")
I think everything looks good now that I understand the issue but can we keep it the old name rather than uuid?

2023-10-16 18:41 UTC, AlexErrant commented on packages/crsqlite-wasm/src/TX.ts
> +    const id = crypto.randomUUID().replaceAll("-", "")
I put a few more braincells into this and I think I can give an example of why there should be unique savepoint names.

Example 1:
```
1. SAVEPOINT a     then tx stack is a
2. SAVEPOINT b                      ab
3. RELEASE b, _but it throws_       ab
4. caught in a's catch, which does
5.     ROLLBACK TO a                a     (b is canceled; docs say "All intervening SAVEPOINTs are canceled")
6.     RELEASE a                    commit nothing
```

Example 2:
```
1. SAVEPOINT a     then tx stack is a
2. SAVEPOINT a                      aa
3. RELEASE a, _but it throws_       aa
4. caught in first a's catch, which does
5.     ROLLBACK TO a                aa
6.     RELEASE a                    a     (commit nothing because tx stack is populated)
```

However, we're now in a weird state with Example 2 because we're out of scope of relevant try/catches. Also, any subsequent attempts to write to the db will never commit.

2023-10-17 14:58 UTC, tantaman commented
I'll merge this today. I also need to update core extension code in `cr-sqlite` base on these learnings 😬

2023-10-17 16:16 UTC, AlexErrant commented
Gonna assume here that

> Error: unrecognized token: "496204c772af430b9c19a3a0df61094d"

is due to starting with a numeric

```
sqlite> savepoint 2good4u;
Parse error: unrecognized token: "2good4u"
  savepoint 2good4u;
            ^--- error here
sqlite> savepoint x2good4u;
sqlite>
```

2023-10-17 21:10 UTC, tantaman approved these changes

2023-10-19 18:57 UTC, merged